#!/usr/bin/env bash
set -euo pipefail

TAG="${1:-}"
OUT_DIR="${2:-docs/compat/reports}"

if [ -z "$TAG" ]; then
  echo "Usage: $0 <rustdesk-tag> [out-dir]" >&2
  exit 2
fi

if ! command -v git >/dev/null 2>&1; then
  echo "git is required" >&2
  exit 2
fi

mkdir -p "$OUT_DIR"
OUT_DIR_ABS="$(cd "$OUT_DIR" && pwd)"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

REPORT="$OUT_DIR_ABS/api-hints-${TAG}.md"

cat > "$REPORT" <<MD
# RustDesk ${TAG} API hint report

This report is generated by scanning upstream source text for API-like paths and compatibility keywords.
It is a hint list, not a proof of API behavior.

MD

echo "Cloning rustdesk/rustdesk tag ${TAG}..." >&2
git clone --depth 1 --branch "$TAG" https://github.com/rustdesk/rustdesk.git "$WORKDIR/rustdesk" >/dev/null 2>&1 || {
  echo "Unable to clone tag ${TAG}; try a branch or release tag that exists upstream." >&2
  exit 1
}

cd "$WORKDIR/rustdesk"

cat >> "$REPORT" <<'MD'
## API-like paths

```text
MD

grep -RInE '"/(api|admin|lic|auth|oidc|ab|devices|users|strategies|device-groups|user-groups|audit|record)[A-Za-z0-9_./{}:-]*"' . \
  --exclude-dir=.git \
  --exclude='*.png' \
  --exclude='*.jpg' \
  --exclude='*.jpeg' \
  --exclude='*.ico' \
  --exclude='*.lock' \
  | head -n 300 >> "$REPORT" || true

cat >> "$REPORT" <<'MD'
```

## Compatibility keywords

```text
MD

grep -RInE 'login-options|currentUser|sysinfo_ver|devices/deploy|devices/cli|plugin-sign|oidc/auth|auth-query|server-config|client-config|capabilities|privacy|monitor|restart' . \
  --exclude-dir=.git \
  --exclude='*.png' \
  --exclude='*.jpg' \
  --exclude='*.jpeg' \
  --exclude='*.ico' \
  --exclude='*.lock' \
  | head -n 500 >> "$REPORT" || true

cat >> "$REPORT" <<'MD'
```

## Suggested next checks

- Compare new hints with `docs/API_MATRIX.md`.
- Add stable aliases for harmless public probes.
- Do not auto-change login, authorization, OIDC, license, or plugin-sign behavior without real client tests.
- Run `bash scripts/compat/smoke-api.sh` after any change.
MD

echo "$REPORT"
